"""Create Timer

Revision ID: 503b50886979
Revises:
Create Date: 2025-12-25 15:04:03.485293

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "503b50886979"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timer",
        sa.Column("название", sa.String(length=200), nullable=False),
        sa.Column("время помидора", sa.Integer(), nullable=False),
        sa.Column("время перерыва", sa.Integer(), nullable=False),
        sa.Column("время долгого перерыва", sa.Integer(), nullable=False),
        sa.Column("количество помидоров", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timer")
    # ### end Alembic commands ###
